### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by klimamat** [Jan-Sebek/DPP_trasa#1]
Po posledních commitech mi kód po zadání stanic vždycky vyhodí segmentation fault, něco se tam bude dít podivného s pamětí...

**Comment by Jan-Sebek** [comment]
Mně se chybu bohužel nepodařilo zreplikovat

**Comment by klimamat** [comment]
Už jsem to objevil - v konstruktoru Stop::Stop() máte datové typy u inicializací proměnných - tzn. deklarujete lokální proměnné se stejným názvem a objekt není inicializovaný, pak se to chová na různých strojích všelijak, já měl například v m_sameStop hodnoty -1 a pak se špatně počítaly ty zprůměrované souřadnice. Takže to chce takhle:

```
Stop::Stop()
{
	m_code = "";
	m_name = "";
	m_sameStop = 0;
	m_lat = 0.0;
	m_long = 0.0;
	m_path_len = 0;
	m_distance = 0;
	h = 0.0;
	visited = false;
	previous = "";
}
```

**Comment by klimamat** [comment]
No a dále k tomu prohledávacímu algoritmu - abyste našli správně nejkratší cestu, je opravdu potřeba upravit tu podmínku, které vrcholy budete vkládát do fronty. Tak abyste tam znova vložili i ty už navštívené vrcholy, do kterých jste právě našli kratší cestu.

Já jsem místo
`if (s_list[neigh.first].visited) { continue; };`
použil
`if (s_list[neigh.first].getPathL() > 1.0e-12 && s_list[neigh.first].getPathL() < tmp.getPathL() + neigh.second) { continue; };`

Pak už mi to např. na Kobylisy -> Pod Karlovem vrátilo očekávanou trasu metro+tramvaj a zkrátila se z 795 na 645 s.

Tohle btw ještě není A*, ale Dijkstra, ale vypadá to, že to pro tenhle graf dostačuje. Abyste to upravili na A*, tak by tam bylo potřeba ještě zapojit tu heuristiku.

**Comment by Jan-Sebek** [comment]
Dobrý den,
opravil jsem nedostatky v kódu ale heuristiku se mi bohužel implementovat nepodařilo. Mohl bych vás požádat o zápočet pro naši skupinu ?
Děkuji Šebek
